vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
    mappings:
       user_images:
           uri_prefix: /img/banner
           upload_destination: '%kernel.project_dir%/public/img/banner'
